[package]
name = "cosmo_store"
version = "0.1.1"
authors = ["Kunjan Dalal <kunjee17@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
uuid = "0.8"
async-trait = "0.1"
anyhow = "1.0"
