[package]
name = "cosmo_store"
version = "0.1.1"
authors = ["Kunjan Dalal <kunjee17@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0"
uuid = "1"
async-trait = "0"
anyhow = "1"
